"""Add category to tips

Revision ID: 42c97211d543
Revises: 1b662c0ed939
Create Date: 2026-04-09 10:23:57.614053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c97211d543'
down_revision = '1b662c0ed939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tips', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
