"""add market table

Revision ID: 95f20ebb8ebb
Revises: 0e67b18496ea
Create Date: 2026-04-09 15:44:23.654673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f20ebb8ebb'
down_revision = '0e67b18496ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('seller_phone', sa.String(length=20), nullable=True),
    sa.Column('seller_location', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_items')
    # ### end Alembic commands ###
